import type { Business } from "./types";

export const CURATED: Business[] = [
  // --- SCARBOROUGH / TORONTO (ON) ---
  {
    id: "cur-001",
    slug: "hopper-hut",
    name: "Hopper Hut",
    tamilName: "ஹாப்பர் ஹட்",
    category: "restaurants-takeout",
    city: "Scarborough",
    province: "ON",
    address: "880 Ellesmere Rd, Scarborough, ON M1P 2W6",
    phone: "+1 416-299-4311",
    website: "https://hopperhut.shop/",
    email: "",
    description:
      "A Scarborough landmark since the mid-1990s for hoppers, kothu roti, string hoppers, and everyday Tamil home-style curries. Located in the Ellesmere & Kennedy plaza.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-002",
    slug: "martins-bakery",
    name: "Martin's Bakery",
    tamilName: "மார்ட்டின் பேக்கரி",
    category: "bakeries-sweets",
    city: "Scarborough",
    province: "ON",
    address: "2761 Markham Rd, Unit B-15, Scarborough, ON M1X 0A4",
    phone: "+1 416-535-2323",
    website: "https://www.martinsbakery.ca/",
    email: "martinsbakery.payment@gmail.com",
    description:
      "Long-running Tamil bakery known for mutton rolls, butter-chicken rolls, egg roti, vadai, pastries, and short eats. A Malvern & Markham Road community staple.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-003",
    slug: "babu-takeout-and-catering",
    name: "Babu Takeout And Catering",
    tamilName: "பாபு டேக்அவுட் & கேட்டரிங்",
    category: "catering-event-food",
    city: "Scarborough",
    province: "ON",
    address: "4800 Sheppard Ave E, Unit 201-204, Scarborough, ON M1S 4N5",
    phone: "+1 416-298-2228",
    website: "http://www.babudelivery.ca/",
    email: "orders@babudelivery.ca",
    description:
      "Renowned family takeout and catering since the 1980s — fresh hoppers, short eats, mutton rolls, and banquet trays for weddings and family events across the GTA.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-004",
    slug: "canbe-foods-inc",
    name: "Canbe Foods Inc",
    tamilName: "கேன்பீ உணவுகள்",
    category: "restaurants-takeout",
    city: "Scarborough",
    province: "ON",
    address: "1760 Ellesmere Rd, Scarborough, ON M1H 2T9",
    phone: "+1 416-298-2219",
    website: "https://www.canbefoods.com/",
    email: "info@canbefoods.com",
    description:
      "Since 1994, Canbe has served authentic South Indian and Sri Lankan curries, roti, kothu, samosas, and catering banquets across East Toronto.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-005",
    slug: "new-kalyani-restaurant",
    name: "New Kalyani Restaurant",
    tamilName: "நியூ கல்யாணி உணவகம்",
    category: "restaurants-takeout",
    city: "Scarborough",
    province: "ON",
    address: "723 Kennedy Rd, Scarborough, ON M1K 2C6",
    phone: "+1 416-261-2678",
    website: "",
    email: "",
    description:
      "One of Scarborough’s earliest Tamil restaurants (roots in the 1980s) — authentic Jaffna-style rice and curry plates, late-night kothu, and sea fish curries.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-006",
    slug: "motherland-foods",
    name: "Motherland Foods",
    tamilName: "மதர்லேண்ட் சூப்பர்மார்க்கெட்",
    category: "grocery-supermarkets",
    city: "Scarborough",
    province: "ON",
    address: "1286 Kennedy Rd #5, Scarborough, ON M1P 2L5",
    phone: "+1 416-751-2444",
    website: "https://motherlandgrocery.ca/",
    email: "",
    description:
      "Premier Tamil & South Asian supermarket — imported Jaffna spices, fresh produce, frozen hopper mixes, palm jaggery, and snacks.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-007",
    slug: "aathavan-unavakam",
    name: "Aathavan Unavakam",
    tamilName: "ஆதவன் உணவகம்",
    category: "restaurants-takeout",
    city: "Scarborough",
    province: "ON",
    address: "501 Passmore Ave, Unit 28, Scarborough, ON M1V 5G4",
    phone: "+1 647-656-5690",
    website: "https://aathavanunavakam.ca/",
    email: "",
    description:
      "Jaffna-style unavakam — traditional banana leaf rice packets, hot mutton kothu, pittu, and home-style curries in North Scarborough.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-008",
    slug: "confused-kitchen",
    name: "Confused Kitchen",
    tamilName: "கன்புயூஸ்டு கிச்சன்",
    category: "restaurants-takeout",
    city: "Scarborough",
    province: "ON",
    address: "5005 Steeles Ave E, Unit 107, Scarborough, ON M1V 5K1",
    phone: "+1 416-292-3313",
    website: "https://www.confusedkitchen.ca/",
    email: "",
    description:
      "Modern fusion Sri Lankan kitchen at Steeles & Markham — popular for kothu boxes, fusion burgers, loaded fries, and late-night eats.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-009",
    slug: "sri-varasiththi-vinaayagar-hindu-temple",
    name: "Sri Varasiththi Vinaayagar Hindu Temple",
    tamilName: "ஸ்ரீ வரசித்தி விநாயகர் ஆலயம்",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "2701 Markham Rd, Scarborough, ON M1X 1M4",
    phone: "+1 416-299-5006",
    website: "https://www.vinaayagar.com/",
    email: "info@vinaayagar.com",
    description:
      "One of Canada’s largest and oldest Tamil Hindu temples on Markham Road — daily poojas, major festivals, Tamil classes, and community hall.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-010",
    slug: "thangam-jewellers",
    name: "Thangam Jewellers",
    tamilName: "தங்கம் ஜூவல்லர்ஸ்",
    category: "fashion-jewellery",
    city: "Scarborough",
    province: "ON",
    address: "2655 Lawrence Ave E, Unit 3, Scarborough, ON M1P 2S2",
    phone: "+1 416-750-1818",
    website: "",
    email: "",
    description:
      "Traditional 22K gold jewelry, wedding thali chains, bangles, and custom gemstone designs for Tamil weddings and milestones.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-011",
    slug: "kumaran-law-office",
    name: "Kumaran Law & Immigration Practice",
    tamilName: "குமரன் சட்ட அலுவலகம்",
    category: "legal-immigration",
    city: "Scarborough",
    province: "ON",
    address: "2061 McCowan Rd, Scarborough, ON M1S 3Y6",
    phone: "+1 416-292-9444",
    website: "",
    email: "info@kumaranlaw.ca",
    description:
      "Immigration, refugee appeals, family sponsorships, real estate closings, and notary services in Tamil and English.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-012",
    slug: "siva-cpa-accounting",
    name: "Sivalingam CPA Professional Corporation",
    tamilName: "சிவNonUser கணக்கியல் & வரி சேவை",
    category: "accounting-financial",
    city: "Scarborough",
    province: "ON",
    address: "2300 Lawrence Ave E, Scarborough, ON M1P 2R2",
    phone: "+1 416-752-8880",
    website: "",
    email: "tax@sivacpa.ca",
    description:
      "Corporate tax planning, personal tax filing, CRA audits, bookkeeping, and payroll services for GTA Tamil business owners.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-013",
    slug: "canadian-tamil-congress",
    name: "Canadian Tamil Congress (CTC)",
    tamilName: "கனடிய தமிழ் காங்கிரஸ்",
    category: "temples-community",
    city: "Toronto",
    province: "ON",
    address: "2954 Finch Ave E, Toronto, ON M1W 2T8",
    phone: "+1 416-240-0078",
    website: "https://www.canadiantamilcongress.ca/",
    email: "info@canadiantamilcongress.ca",
    description:
      "National non-profit advocacy organization serving Tamil Canadians — civic engagement, heritage month events, and leadership mentorship.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-014",
    slug: "cmr-tamil-fm-101-3",
    name: "CMR Tamil FM 101.3 (Canadian Multicultural Radio)",
    tamilName: "சிஎம்ஆர் தமிழ் பண்பலை",
    category: "media-publishing",
    city: "Toronto",
    province: "ON",
    address: "30 Interchange Way, Toronto, ON L4K 5C3",
    phone: "+1 416-621-0100",
    website: "https://cmr24.net/",
    email: "tamil@cmr24.net",
    description:
      "Canada’s flagship 24/7 Tamil broadcast radio station — community news, diaspora talk shows, music, and local business spotlights.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-015",
    slug: "sri-ayyappa-samajam-ontario",
    name: "Sri Ayyappa Samajam of Ontario",
    tamilName: "ஸ்ரீ ஐயப்ப சமாஜம் ஒன்ராறியோ",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "635 Middlefield Rd, Scarborough, ON M1V 5B8",
    phone: "+1 416-321-6104",
    website: "https://ayyappasooriyam.com/",
    email: "",
    description:
      "Historic Hindu temple on Middlefield Rd serving the Tamil community with daily pujas, Mandalam season pilgrimages, and cultural school.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- MARKHAM / YORK REGION (ON) ---
  {
    id: "cur-016",
    slug: "subiksha-supermarket-markham",
    name: "Subiksha Supermarket",
    tamilName: "சுபிக்ஷா சூப்பர்மார்க்கெட்",
    category: "grocery-supermarkets",
    city: "Markham",
    province: "ON",
    address: "7690 Markham Rd, Unit 1, Markham, ON L3S 4S1",
    phone: "+1 905-294-8882",
    website: "",
    email: "",
    description:
      "Extensive Tamil grocery store in Markham — fresh South Asian vegetables, Jaffna curry powders, snacks, sweets, and household essentials.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-017",
    slug: "richmond-hill-hindu-temple",
    name: "Hindu Temple Society of Canada (Richmond Hill)",
    tamilName: "ரிச்மண்ட் ஹில் இந்து ஆலயம்",
    category: "temples-community",
    city: "Richmond Hill",
    province: "ON",
    address: "10865 Bayview Ave, Richmond Hill, ON L4S 1M1",
    phone: "+1 905-883-9109",
    website: "https://www.thehindutemple.ca/",
    email: "info@thehindutemple.ca",
    description:
      "Prominent architectural temple in York Region — daily pooja rituals, Tamil language classes, Navarathri festivals, and classical dance performances.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-018",
    slug: "gana-kadai-markham",
    name: "Gana Kadai Sri Lankan Cuisine",
    tamilName: "கானா கடை",
    category: "restaurants-takeout",
    city: "Markham",
    province: "ON",
    address: "9566 Markham Rd, Markham, ON L6E 0W1",
    phone: "+1 905-554-4262",
    website: "https://ganakadai.ca/",
    email: "",
    description:
      "Authentic Ceylon rolls, spicy crab curry, chicken kothu, and weekend banana leaf specials in north Markham.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-019",
    slug: "kavi-realty-markham",
    name: "Kavi Rajah Real Estate Group",
    tamilName: "கவி ராஜா ரியல் எஸ்டேட்",
    category: "real-estate-property",
    city: "Markham",
    province: "ON",
    address: "8300 Woodbine Ave, Markham, ON L3R 9Y7",
    phone: "+1 416-890-5555",
    website: "",
    email: "kavi@gtawealthrealty.ca",
    description:
      "Residential & commercial real estate, pre-construction investments, and mortgage pre-approvals across Markham, Stouffville, and Richmond Hill.",
    verified: true,
    featured: false,
    source: "curated",
  },
  {
    id: "cur-020",
    slug: "markham-tamil-driving-school",
    name: "Markham & Scarborough Tamil Driving School",
    tamilName: "தமிழ் டிரைவிங் பள்ளி",
    category: "tuition-education",
    city: "Markham",
    province: "ON",
    address: "5990 14th Ave, Markham, ON L3S 4M9",
    phone: "+1 416-838-2345",
    website: "",
    email: "",
    description:
      "MTO-certified driving instructors offering G2 and G road test preparation in Tamil and English with high first-time pass rates.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- BRAMPTON / MISSISSAUGA / PEEL REGION (ON) ---
  {
    id: "cur-021",
    slug: "nila-supermarket-brampton",
    name: "Nila Supermarket",
    tamilName: "நிலா சூப்பர்மார்க்கெட்",
    category: "grocery-supermarkets",
    city: "Brampton",
    province: "ON",
    address: "9445 Mississauga Rd, Unit 1, Brampton, ON L6X 0Z8",
    phone: "+1 905-455-6452",
    website: "",
    email: "",
    description:
      "West GTA favourite for Tamil and Sri Lankan spices, fresh fish, banana leaves, snacks, idli batter, and seasonal mangoes.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-022",
    slug: "spicy-feast-mississauga",
    name: "Spicy Feast Sri Lankan Restaurant",
    tamilName: "ஸ்பைசி ஃபீஸ்ட் உணவகம்",
    category: "restaurants-takeout",
    city: "Mississauga",
    province: "ON",
    address: "3024 Hurontario St, Mississauga, ON L5B 4M4",
    phone: "+1 905-276-8800",
    website: "",
    email: "",
    description:
      "Cooked-to-order kothu roti, devilled beef/chicken, lamprais parcels, and seafood curries in Central Mississauga.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-023",
    slug: "mayura-bridal-salon-brampton",
    name: "Mayura Bridal & Beauty Salon",
    tamilName: "மயூரா பிரைடல் சலூன்",
    category: "salons-beauty",
    city: "Brampton",
    province: "ON",
    address: "10 Cottrelle Blvd, Brampton, ON L6S 0E2",
    phone: "+1 905-790-2211",
    website: "",
    email: "",
    description:
      "Bridal hair & makeup, saree draping, mehendi, facials, and grooming for Tamil weddings and celebrations across Peel Region.",
    verified: true,
    featured: false,
    source: "curated",
  },
  {
    id: "cur-024",
    slug: "siva-auto-care-mississauga",
    name: "Siva Auto Care & Mechanics",
    tamilName: "சிவா ஆட்டோ மெக்கானிக்",
    category: "auto-mechanics",
    city: "Mississauga",
    province: "ON",
    address: "1230 Aimco Blvd, Mississauga, ON L4W 1B2",
    phone: "+1 905-625-7482",
    website: "",
    email: "",
    description:
      "Safety certifications, brake repairs, engine diagnostics, oil changes, and winter tire changeovers.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- AJAX / PICKERING / DURHAM REGION (ON) ---
  {
    id: "cur-025",
    slug: "durham-tamil-catering-ajax",
    name: "Durham Tamil Takeout & Catering",
    tamilName: "டர்காம் தமிழ் டேக்அவுட்",
    category: "catering-event-food",
    city: "Ajax",
    province: "ON",
    address: "269 Kingston Rd E, Ajax, ON L1Z 0K9",
    phone: "+1 905-428-1122",
    website: "",
    email: "",
    description:
      "Weekend hoppers, spicy cutlets, mutton rolls, and bulk catering orders for Durham Region Tamil families in Ajax, Pickering, and Whitby.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-026",
    slug: "pickering-tamil-tuition-centre",
    name: "Pickering Tamil & Math Academy",
    tamilName: "பிக்கரிங் தமிழ் கல்வி மையம்",
    category: "tuition-education",
    city: "Pickering",
    province: "ON",
    address: "1355 Kingston Rd, Pickering, ON L1V 1B8",
    phone: "+1 905-831-7788",
    website: "",
    email: "",
    description:
      "Tamil language literacy, classical Carnatic music lessons, and tutoring in high school math and sciences.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- OTTAWA & EASTERN ONTARIO ---
  {
    id: "cur-027",
    slug: "ottawa-tamil-association",
    name: "Ottawa Tamil Association (OTA)",
    tamilName: "ஒட்டாவா தமிழ் சங்கம்",
    category: "temples-community",
    city: "Ottawa",
    province: "ON",
    address: "Ottawa, ON",
    phone: "+1 613-288-8264",
    website: "https://ottawatamilassociation.ca/",
    email: "info@ottawatamilassociation.ca",
    description:
      "Connecting Tamil families across the National Capital Region — community sports, cultural days, youth programs, and language classes.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-028",
    slug: "tamarind-tiffin-ottawa",
    name: "Tamarind Tiffin Sri Lankan Kitchen",
    tamilName: "தமரிண்ட் டிபன்",
    category: "restaurants-takeout",
    city: "Ottawa",
    province: "ON",
    address: "1055 Bank St, Ottawa, ON K1S 3W9",
    phone: "+1 613-730-1010",
    website: "",
    email: "",
    description:
      "Authentic Ceylon curries, string hoppers, devilled cuttlefish, and vegetable kothu in the heart of Ottawa.",
    verified: true,
    featured: true,
    source: "curated",
  },

  // --- HAMILTON, KITCHENER, WATERLOO, LONDON (ON) ---
  {
    id: "cur-029",
    slug: "hamilton-tamil-cultural-association",
    name: "Hamilton Tamil Cultural Association",
    tamilName: "ஹாமில்டன் தமிழ் கலாச்சார சங்கம்",
    category: "temples-community",
    city: "Hamilton",
    province: "ON",
    address: "Hamilton, ON",
    phone: "+1 905-525-9140",
    website: "",
    email: "hamiltontamil@gmail.com",
    description:
      "Community hub supporting Tamil families, McMaster university students, and newcomers in Hamilton, Ancaster, and Burlington.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-030",
    slug: "waterloo-ceylon-kitchen",
    name: "Waterloo Ceylon Kitchen",
    tamilName: "வாட்டர்லூ சிலோன் கிச்சன்",
    category: "restaurants-takeout",
    city: "Waterloo",
    province: "ON",
    address: "255 King St N, Waterloo, ON N2J 4V2",
    phone: "+1 519-886-9090",
    website: "",
    email: "",
    description:
      "Popular spot for University of Waterloo and Laurier students & local tech professionals craving spicy kothu, rolls, and curries.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-031",
    slug: "london-tamil-community-services",
    name: "London Tamil Association & Services",
    tamilName: "லண்டன் தமிழ் சங்கம்",
    category: "temples-community",
    city: "London",
    province: "ON",
    address: "London, ON",
    phone: "+1 519-661-2111",
    website: "",
    email: "info@londontamils.ca",
    description:
      "Community organization in Southwestern Ontario coordinating Tamil school, cultural celebrations, and newcomer support.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- MONTREAL & QUEBEC (QC) ---
  {
    id: "cur-032",
    slug: "nanthus-bakery-montreal",
    name: "Nanthu's Bakery Kitchen",
    tamilName: "நந்துஸ் பேக்கரி & கிச்சன்",
    category: "bakeries-sweets",
    city: "Montreal",
    province: "QC",
    address: "6953 Victoria Ave, Montreal, QC H3W 2T6",
    phone: "+1 438-229-1768",
    website: "",
    email: "",
    description:
      "Iconic Montreal Tamil bakery on Victoria Avenue in Côte-des-Neiges — fresh mutton rolls, egg pastries, milk toffee, and daily short eats.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-033",
    slug: "montreal-durkai-amman-temple",
    name: "Sri Durkai Amman Temple Montreal",
    tamilName: "மொண்ட்ரியால் ஸ்ரீ துர்க்கை அம்மன் கோவில்",
    category: "temples-community",
    city: "Montreal",
    province: "QC",
    address: "2465 Rue Bélanger, Montréal, QC H2G 1E4",
    phone: "+1 514-722-7779",
    website: "",
    email: "",
    description:
      "The spiritual and cultural heartbeat of the Quebec Tamil community, hosting daily pujas, chariot festival (Ther), and cultural festivities.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-034",
    slug: "colombo-curry-house-montreal",
    name: "Colombo Curry House",
    tamilName: "கொழும்பு கறி ஹவுஸ்",
    category: "restaurants-takeout",
    city: "Montreal",
    province: "QC",
    address: "5155 Chemin Queen Mary, Montréal, QC H3W 1X4",
    phone: "+1 514-484-8882",
    website: "",
    email: "",
    description:
      "Traditional Sri Lankan Tamil curries, devilled pork/chicken, kothu roti, and weekend string hopper banquets.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-035",
    slug: "laval-tamil-grocery-services",
    name: "Laval Tamil Grocers & Spice House",
    tamilName: "லாவால் தமிழ் மளிகை",
    category: "grocery-supermarkets",
    city: "Laval",
    province: "QC",
    address: "1450 Boulevard Curé-Labelle, Laval, QC H7V 2W2",
    phone: "+1 450-681-4455",
    website: "",
    email: "",
    description:
      "Serving North Shore Montreal families with fresh produce, rice bags, South Indian masalas, and Sri Lankan snacks.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- VANCOUVER & METRO VANCOUVER (BC) ---
  {
    id: "cur-036",
    slug: "thurga-foods-vancouver",
    name: "Thurga Foods",
    tamilName: "துர்கா உணவுகள்",
    category: "grocery-supermarkets",
    city: "Vancouver",
    province: "BC",
    address: "6049 Fraser St, Vancouver, BC V5W 2Z8",
    phone: "+1 604-325-1100",
    website: "",
    email: "",
    description:
      "Metro Vancouver's primary Sri Lankan and Tamil grocery store on Fraser Street — Ceylon spices, frozen foods, hopper flour, and imported specialties.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-037",
    slug: "vancouver-murugan-temple",
    name: "B.C. Murugan Temple",
    tamilName: "பிரிட்டிஷ் கொலம்பியா முருகன் கோவில்",
    category: "temples-community",
    city: "Vancouver",
    province: "BC",
    address: "3134 140 St, Surrey, BC V4P 2B3",
    phone: "+1 604-536-7494",
    website: "https://bcmurugantemple.com/",
    email: "info@bcmurugantemple.com",
    description:
      "Central Hindu temple for BC Tamils — holy sanctum of Lord Murugan, conducting Thaipusam festivals, wedding blessings, and community meals.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-038",
    slug: "lanka-palace-surrey",
    name: "Lanka Palace Restaurant",
    tamilName: "லங்கா பேலஸ் உணவகம்",
    category: "restaurants-takeout",
    city: "Surrey",
    province: "BC",
    address: "9340 120 St, Surrey, BC V3V 4B9",
    phone: "+1 604-588-7711",
    website: "",
    email: "",
    description:
      "Sri Lankan Tamil dining in Fraser Valley — delicious seafood kothu, lamprais, hopper combos, and family-size weekend takeout trays.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-039",
    slug: "west-coast-tamil-law-burnaby",
    name: "West Coast Tamil Legal & Notary Services",
    tamilName: "வெஸ்ட் கோஸ்ட் தமிழ் சட்ட சேவை",
    category: "legal-immigration",
    city: "Burnaby",
    province: "BC",
    address: "4720 Kingsway, Burnaby, BC V5H 4N2",
    phone: "+1 604-434-2200",
    website: "",
    email: "legal@westcoasttamil.ca",
    description:
      "Real estate conveyancing, BC PNP immigration, family law, and commissioner of oaths serving Metro Vancouver Tamils.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- CALGARY & EDMONTON (AB) ---
  {
    id: "cur-040",
    slug: "calgary-murugan-temple",
    name: "Sri Murugan Society of Alberta (Calgary)",
    tamilName: "கல்கரி ஸ்ரீ முருகன் ஆலயம்",
    category: "temples-community",
    city: "Calgary",
    province: "AB",
    address: "4203 17 Ave SE, Calgary, AB T2A 0T2",
    phone: "+1 403-248-2838",
    website: "https://calgarymurugantemple.ca/",
    email: "info@calgarymurugantemple.ca",
    description:
      "Cultural & spiritual pillar for Alberta Tamils — daily pujas, Tamil school, Deepavali celebrations, and senior gatherings.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-041",
    slug: "ceylon-flavours-calgary",
    name: "Ceylon Flavours Restaurant & Takeout",
    tamilName: "சிலோன் ஃப்ளேவர்ஸ்",
    category: "restaurants-takeout",
    city: "Calgary",
    province: "AB",
    address: "3770 Westwinds Dr NE, Calgary, AB T3J 5H3",
    phone: "+1 403-293-6622",
    website: "",
    email: "",
    description:
      "Calgary's hot spot for Ceylon short eats, spicy mutton kothu, egg roti, and weekend Jaffna seafood curries.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-042",
    slug: "edmonton-maha-ganapathy-temple",
    name: "Maha Ganapathy Temple of Edmonton",
    tamilName: "எட்மண்டன் மகா கணபதி ஆலயம்",
    category: "temples-community",
    city: "Edmonton",
    province: "AB",
    address: "12838 52 St NW, Edmonton, AB T5A 3P8",
    phone: "+1 780-478-2244",
    website: "https://mahaganapathy.com/",
    email: "info@mahaganapathy.com",
    description:
      "Traditional granite deity temple serving Northern Alberta Tamil families with youth chanting, weddings, and grand annual festivals.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-043",
    slug: "jaffna-tiffins-edmonton",
    name: "Jaffna Tiffins & Spices Edmonton",
    tamilName: "யாழ்ப்பாணம் டிபன் & மசாலா",
    category: "restaurants-takeout",
    city: "Edmonton",
    province: "AB",
    address: "9210 34 Ave NW, Edmonton, AB T6E 5P2",
    phone: "+1 780-462-8811",
    website: "",
    email: "",
    description:
      "Authentic Northern Sri Lankan style dosai, mutton curries, kothu, and catering across Edmonton and surrounding communities.",
    verified: true,
    featured: true,
    source: "curated",
  },

  // --- WINNIPEG (MB) ---
  {
    id: "cur-044",
    slug: "manitoba-tamil-cultural-association",
    name: "Manitoba Tamil Cultural Association (MTCA)",
    tamilName: "மனிடோபா தமிழ் கலாச்சார சங்கம்",
    category: "temples-community",
    city: "Winnipeg",
    province: "MB",
    address: "Winnipeg, MB",
    phone: "+1 204-474-8800",
    website: "https://manitobatamils.com/",
    email: "contact@manitobatamils.com",
    description:
      "Uniting Tamil families across Manitoba — organizing Tamil New Year, Pongal festivals, youth sports leagues, and settlement guidance.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-045",
    slug: "spicy-banana-leaf-winnipeg",
    name: "Spicy Banana Leaf Sri Lankan Eats",
    tamilName: "ஸ்பைசி பனானா லீப்",
    category: "restaurants-takeout",
    city: "Winnipeg",
    province: "MB",
    address: "1855 Pembina Hwy, Winnipeg, MB R3T 2G6",
    phone: "+1 204-269-1234",
    website: "",
    email: "",
    description:
      "Authentic Ceylon curries, flaky roti, kothu, and short eats for Winnipeg and University of Manitoba students.",
    verified: true,
    featured: true,
    source: "curated",
  },

  // --- HALIFAX & ATLANTIC CANADA (NS / NL / NB / PE) ---
  {
    id: "cur-046",
    slug: "halifax-tamil-cultural-society",
    name: "Tamil Cultural Society of Nova Scotia",
    tamilName: "நோவா ஸ்கோஷியா தமிழ் கலாச்சார சங்கம்",
    category: "temples-community",
    city: "Halifax",
    province: "NS",
    address: "Halifax, NS",
    phone: "+1 902-420-5555",
    website: "",
    email: "novascotiatamils@gmail.com",
    description:
      "Active Atlantic Canada Tamil society connecting families, Dalhousie and Saint Mary's students, and healthcare professionals in Halifax & Dartmouth.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-047",
    slug: "st-johns-tamil-community-nl",
    name: "Newfoundland Tamil Community Association",
    tamilName: "நியூஃபவுண்ட்லாந்து தமிழ் சங்கம்",
    category: "temples-community",
    city: "St. John's",
    province: "NL",
    address: "St. John's, NL",
    phone: "+1 709-864-8000",
    website: "",
    email: "nltamils@gmail.com",
    description:
      "Community hub supporting Tamil families, physicians, engineers, and Memorial University scholars across Newfoundland & Labrador.",
    verified: true,
    featured: true,
    source: "curated",
  },

  // --- SASKATOON & REGINA (SK) ---
  {
    id: "cur-048",
    slug: "saskatoon-tamil-association",
    name: "Saskatoon Tamil Community Association",
    tamilName: "சாஸ்கடூன் தமிழ் சங்கம்",
    category: "temples-community",
    city: "Saskatoon",
    province: "SK",
    address: "Saskatoon, SK",
    phone: "+1 306-966-4343",
    website: "",
    email: "saskatoontamils@gmail.com",
    description:
      "Connecting Tamil residents in Saskatoon and the University of Saskatchewan campus with cultural events and language classes.",
    verified: true,
    featured: true,
    source: "curated",
  },

  // --- NATIONWIDE ONLINE SERVICES ---
  {
    id: "cur-049",
    slug: "tamilkadai-canada",
    name: "Tamilkadai Canada",
    tamilName: "தமிழ்கடை கனடா",
    category: "grocery-supermarkets",
    city: "Toronto",
    province: "ON",
    address: "Nationwide Online Store, Toronto, ON",
    phone: "+1 647-558-8822",
    website: "https://www.tamilkadai.ca/",
    email: "support@tamilkadai.ca",
    description:
      "Canada’s leading online Tamil grocery service shipping authentic spices, snacks, Jaffna curry powders, sweets, and cookware coast-to-coast.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-050",
    slug: "express-tamil-printing-canada",
    name: "Express Tamil Printing & Invitations",
    tamilName: "எக்ஸ்பிரஸ் தமிழ் பிரிண்டிங்",
    category: "printing-design",
    city: "Scarborough",
    province: "ON",
    address: "1920 Ellesmere Rd, Scarborough, ON M1H 2V6",
    phone: "+1 416-438-9900",
    website: "",
    email: "print@expresstamil.ca",
    description:
      "Specialists in luxury Tamil wedding invitation cards, event banners, business cards, signage, and temple flyers shipped Canada-wide.",
    verified: true,
    featured: false,
    source: "curated",
  },
];
