import type { Business } from "./types";

export const CURATED: Business[] = [
  // --- SCARBOROUGH / TORONTO (ON) ---
  {
    id: "cur-001",
    slug: "hopper-hut",
    name: "Hopper Hut",
    tamilName: "ஹாப்பர் ஹட்",
    category: "restaurants-takeout",
    city: "Scarborough",
    province: "ON",
    address: "880 Ellesmere Rd, Scarborough, ON M1P 2W6",
    phone: "+1 416-299-4311",
    website: "https://hopperhut.shop/",
    email: "",
    description:
      "A Scarborough landmark since the mid-1990s for hoppers, kothu roti, string hoppers, and everyday Tamil home-style curries. Located in the Ellesmere & Kennedy plaza.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-002",
    slug: "martins-bakery",
    name: "Martin's Bakery",
    tamilName: "மார்ட்டின் பேக்கரி",
    category: "bakeries-sweets",
    city: "Scarborough",
    province: "ON",
    address: "2761 Markham Rd, Unit B-15, Scarborough, ON M1X 0A4",
    phone: "+1 416-535-2323",
    website: "https://www.martinsbakery.ca/",
    email: "martinsbakery.payment@gmail.com",
    description:
      "Long-running Tamil bakery known for mutton rolls, butter-chicken rolls, egg roti, vadai, pastries, and short eats. A Malvern & Markham Road community staple.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-003",
    slug: "babu-takeout-and-catering",
    name: "Babu Takeout And Catering",
    tamilName: "பாபு டேக்அவுட் & கேட்டரிங்",
    category: "catering-event-food",
    city: "Scarborough",
    province: "ON",
    address: "4800 Sheppard Ave E, Unit 201-204, Scarborough, ON M1S 4N5",
    phone: "+1 416-298-2228",
    website: "http://www.babudelivery.ca/",
    email: "orders@babudelivery.ca",
    description:
      "Renowned family takeout and catering since the 1980s — fresh hoppers, short eats, mutton rolls, and banquet trays for weddings and family events across the GTA.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-004",
    slug: "canbe-foods-inc",
    name: "Canbe Foods Inc",
    tamilName: "கேன்பீ உணவுகள்",
    category: "restaurants-takeout",
    city: "Scarborough",
    province: "ON",
    address: "1760 Ellesmere Rd, Scarborough, ON M1H 2T9",
    phone: "+1 416-298-2219",
    website: "https://www.canbefoods.com/",
    email: "info@canbefoods.com",
    description:
      "Since 1994, Canbe has served authentic South Indian and Sri Lankan curries, roti, kothu, samosas, and catering banquets across East Toronto.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-005",
    slug: "new-kalyani-restaurant",
    name: "New Kalyani Restaurant",
    tamilName: "நியூ கல்யாணி உணவகம்",
    category: "restaurants-takeout",
    city: "Scarborough",
    province: "ON",
    address: "723 Kennedy Rd, Scarborough, ON M1K 2C6",
    phone: "+1 416-261-2678",
    website: "",
    email: "",
    description:
      "One of Scarborough’s earliest Tamil restaurants (roots in the 1980s) — authentic Jaffna-style rice and curry plates, late-night kothu, and sea fish curries.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-006",
    slug: "motherland-foods",
    name: "Motherland Foods",
    tamilName: "மதர்லேண்ட் சூப்பர்மார்க்கெட்",
    category: "grocery-supermarkets",
    city: "Scarborough",
    province: "ON",
    address: "1286 Kennedy Rd #5, Scarborough, ON M1P 2L5",
    phone: "+1 416-751-2444",
    website: "https://motherlandgrocery.ca/",
    email: "",
    description:
      "Premier Tamil & South Asian supermarket — imported Jaffna spices, fresh produce, frozen hopper mixes, palm jaggery, and snacks.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-007",
    slug: "aathavan-unavakam",
    name: "Aathavan Unavakam",
    tamilName: "ஆதவன் உணவகம்",
    category: "restaurants-takeout",
    city: "Scarborough",
    province: "ON",
    address: "501 Passmore Ave, Unit 28, Scarborough, ON M1V 5G4",
    phone: "+1 647-656-5690",
    website: "https://aathavanunavakam.ca/",
    email: "",
    description:
      "Jaffna-style unavakam — traditional banana leaf rice packets, hot mutton kothu, pittu, and home-style curries in North Scarborough.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-008",
    slug: "confused-kitchen",
    name: "Confused Kitchen",
    tamilName: "கன்புயூஸ்டு கிச்சன்",
    category: "restaurants-takeout",
    city: "Scarborough",
    province: "ON",
    address: "5005 Steeles Ave E, Unit 107, Scarborough, ON M1V 5K1",
    phone: "+1 416-292-3313",
    website: "https://www.confusedkitchen.ca/",
    email: "",
    description:
      "Modern fusion Sri Lankan kitchen at Steeles & Markham — popular for kothu boxes, fusion burgers, loaded fries, and late-night eats.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-009",
    slug: "sri-varasiththi-vinaayagar-hindu-temple",
    name: "Sri Varasiththi Vinaayagar Hindu Temple",
    tamilName: "ஸ்ரீ வரசித்தி விநாயகர் ஆலயம்",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "2701 Markham Rd, Scarborough, ON M1X 1M4",
    phone: "+1 416-299-5006",
    website: "https://www.vinaayagar.com/",
    email: "info@vinaayagar.com",
    description:
      "One of Canada’s largest and oldest Tamil Hindu temples on Markham Road — daily poojas, major festivals, Tamil classes, and community hall.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-010",
    slug: "thangam-jewellers",
    name: "Thangam Jewellers",
    tamilName: "தங்கம் ஜூவல்லர்ஸ்",
    category: "fashion-jewellery",
    city: "Scarborough",
    province: "ON",
    address: "2655 Lawrence Ave E, Unit 3, Scarborough, ON M1P 2S2",
    phone: "+1 416-750-1818",
    website: "",
    email: "",
    description:
      "Traditional 22K gold jewelry, wedding thali chains, bangles, and custom gemstone designs for Tamil weddings and milestones.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-011",
    slug: "kumaran-law-office",
    name: "Kumaran Law & Immigration Practice",
    tamilName: "குமரன் சட்ட அலுவலகம்",
    category: "legal-immigration",
    city: "Scarborough",
    province: "ON",
    address: "2061 McCowan Rd, Scarborough, ON M1S 3Y6",
    phone: "+1 416-292-9444",
    website: "",
    email: "info@kumaranlaw.ca",
    description:
      "Immigration, refugee appeals, family sponsorships, real estate closings, and notary services in Tamil and English.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-012",
    slug: "siva-cpa-accounting",
    name: "Sivalingam CPA Professional Corporation",
    tamilName: "சிவNonUser கணக்கியல் & வரி சேவை",
    category: "accounting-financial",
    city: "Scarborough",
    province: "ON",
    address: "2300 Lawrence Ave E, Scarborough, ON M1P 2R2",
    phone: "+1 416-752-8880",
    website: "",
    email: "tax@sivacpa.ca",
    description:
      "Corporate tax planning, personal tax filing, CRA audits, bookkeeping, and payroll services for GTA Tamil business owners.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-013",
    slug: "canadian-tamil-congress",
    name: "Canadian Tamil Congress (CTC)",
    tamilName: "கனடிய தமிழ் காங்கிரஸ்",
    category: "temples-community",
    city: "Toronto",
    province: "ON",
    address: "2954 Finch Ave E, Toronto, ON M1W 2T8",
    phone: "+1 416-240-0078",
    website: "https://www.canadiantamilcongress.ca/",
    email: "info@canadiantamilcongress.ca",
    description:
      "National non-profit advocacy organization serving Tamil Canadians — civic engagement, heritage month events, and leadership mentorship.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-014",
    slug: "cmr-tamil-fm-101-3",
    name: "CMR Tamil FM 101.3 (Canadian Multicultural Radio)",
    tamilName: "சிஎம்ஆர் தமிழ் பண்பலை",
    category: "media-publishing",
    city: "Toronto",
    province: "ON",
    address: "30 Interchange Way, Toronto, ON L4K 5C3",
    phone: "+1 416-621-0100",
    website: "https://cmr24.net/",
    email: "tamil@cmr24.net",
    description:
      "Canada’s flagship 24/7 Tamil broadcast radio station — community news, diaspora talk shows, music, and local business spotlights.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-015",
    slug: "sri-ayyappa-samajam-ontario",
    name: "Sri Ayyappa Samajam of Ontario",
    tamilName: "ஸ்ரீ ஐயப்ப சமாஜம் ஒன்ராறியோ",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "635 Middlefield Rd, Scarborough, ON M1V 5B8",
    phone: "+1 416-321-6104",
    website: "https://ayyappasooriyam.com/",
    email: "",
    description:
      "Historic Hindu temple on Middlefield Rd serving the Tamil community with daily pujas, Mandalam season pilgrimages, and cultural school.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- MARKHAM / YORK REGION (ON) ---
  {
    id: "cur-016",
    slug: "subiksha-supermarket-markham",
    name: "Subiksha Supermarket",
    tamilName: "சுபிக்ஷா சூப்பர்மார்க்கெட்",
    category: "grocery-supermarkets",
    city: "Markham",
    province: "ON",
    address: "7690 Markham Rd, Unit 1, Markham, ON L3S 4S1",
    phone: "+1 905-294-8882",
    website: "",
    email: "",
    description:
      "Extensive Tamil grocery store in Markham — fresh South Asian vegetables, Jaffna curry powders, snacks, sweets, and household essentials.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-017",
    slug: "richmond-hill-hindu-temple",
    name: "Hindu Temple Society of Canada (Richmond Hill)",
    tamilName: "ரிச்மண்ட் ஹில் இந்து ஆலயம்",
    category: "temples-community",
    city: "Richmond Hill",
    province: "ON",
    address: "10865 Bayview Ave, Richmond Hill, ON L4S 1M1",
    phone: "+1 905-883-9109",
    website: "https://www.thehindutemple.ca/",
    email: "info@thehindutemple.ca",
    description:
      "Prominent architectural temple in York Region — daily pooja rituals, Tamil language classes, Navarathri festivals, and classical dance performances.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-018",
    slug: "gana-kadai-markham",
    name: "Gana Kadai Sri Lankan Cuisine",
    tamilName: "கானா கடை",
    category: "restaurants-takeout",
    city: "Markham",
    province: "ON",
    address: "9566 Markham Rd, Markham, ON L6E 0W1",
    phone: "+1 905-554-4262",
    website: "https://ganakadai.ca/",
    email: "",
    description:
      "Authentic Ceylon rolls, spicy crab curry, chicken kothu, and weekend banana leaf specials in north Markham.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-019",
    slug: "kavi-realty-markham",
    name: "Kavi Rajah Real Estate Group",
    tamilName: "கவி ராஜா ரியல் எஸ்டேட்",
    category: "real-estate-property",
    city: "Markham",
    province: "ON",
    address: "8300 Woodbine Ave, Markham, ON L3R 9Y7",
    phone: "+1 416-890-5555",
    website: "",
    email: "kavi@gtawealthrealty.ca",
    description:
      "Residential & commercial real estate, pre-construction investments, and mortgage pre-approvals across Markham, Stouffville, and Richmond Hill.",
    verified: true,
    featured: false,
    source: "curated",
  },
  {
    id: "cur-020",
    slug: "markham-tamil-driving-school",
    name: "Markham & Scarborough Tamil Driving School",
    tamilName: "தமிழ் டிரைவிங் பள்ளி",
    category: "tuition-education",
    city: "Markham",
    province: "ON",
    address: "5990 14th Ave, Markham, ON L3S 4M9",
    phone: "+1 416-838-2345",
    website: "",
    email: "",
    description:
      "MTO-certified driving instructors offering G2 and G road test preparation in Tamil and English with high first-time pass rates.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- BRAMPTON / MISSISSAUGA / PEEL REGION (ON) ---
  {
    id: "cur-021",
    slug: "nila-supermarket-brampton",
    name: "Nila Supermarket",
    tamilName: "நிலா சூப்பர்மார்க்கெட்",
    category: "grocery-supermarkets",
    city: "Brampton",
    province: "ON",
    address: "9445 Mississauga Rd, Unit 1, Brampton, ON L6X 0Z8",
    phone: "+1 905-455-6452",
    website: "",
    email: "",
    description:
      "West GTA favourite for Tamil and Sri Lankan spices, fresh fish, banana leaves, snacks, idli batter, and seasonal mangoes.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-022",
    slug: "spicy-feast-mississauga",
    name: "Spicy Feast Sri Lankan Restaurant",
    tamilName: "ஸ்பைசி ஃபீஸ்ட் உணவகம்",
    category: "restaurants-takeout",
    city: "Mississauga",
    province: "ON",
    address: "3024 Hurontario St, Mississauga, ON L5B 4M4",
    phone: "+1 905-276-8800",
    website: "",
    email: "",
    description:
      "Cooked-to-order kothu roti, devilled beef/chicken, lamprais parcels, and seafood curries in Central Mississauga.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-023",
    slug: "mayura-bridal-salon-brampton",
    name: "Mayura Bridal & Beauty Salon",
    tamilName: "மயூரா பிரைடல் சலூன்",
    category: "salons-beauty",
    city: "Brampton",
    province: "ON",
    address: "10 Cottrelle Blvd, Brampton, ON L6S 0E2",
    phone: "+1 905-790-2211",
    website: "",
    email: "",
    description:
      "Bridal hair & makeup, saree draping, mehendi, facials, and grooming for Tamil weddings and celebrations across Peel Region.",
    verified: true,
    featured: false,
    source: "curated",
  },
  {
    id: "cur-024",
    slug: "siva-auto-care-mississauga",
    name: "Siva Auto Care & Mechanics",
    tamilName: "சிவா ஆட்டோ மெக்கானிக்",
    category: "auto-mechanics",
    city: "Mississauga",
    province: "ON",
    address: "1230 Aimco Blvd, Mississauga, ON L4W 1B2",
    phone: "+1 905-625-7482",
    website: "",
    email: "",
    description:
      "Safety certifications, brake repairs, engine diagnostics, oil changes, and winter tire changeovers.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- AJAX / PICKERING / DURHAM REGION (ON) ---
  {
    id: "cur-025",
    slug: "durham-tamil-catering-ajax",
    name: "Durham Tamil Takeout & Catering",
    tamilName: "டர்காம் தமிழ் டேக்அவுட்",
    category: "catering-event-food",
    city: "Ajax",
    province: "ON",
    address: "269 Kingston Rd E, Ajax, ON L1Z 0K9",
    phone: "+1 905-428-1122",
    website: "",
    email: "",
    description:
      "Weekend hoppers, spicy cutlets, mutton rolls, and bulk catering orders for Durham Region Tamil families in Ajax, Pickering, and Whitby.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-026",
    slug: "pickering-tamil-tuition-centre",
    name: "Pickering Tamil & Math Academy",
    tamilName: "பிக்கரிங் தமிழ் கல்வி மையம்",
    category: "tuition-education",
    city: "Pickering",
    province: "ON",
    address: "1355 Kingston Rd, Pickering, ON L1V 1B8",
    phone: "+1 905-831-7788",
    website: "",
    email: "",
    description:
      "Tamil language literacy, classical Carnatic music lessons, and tutoring in high school math and sciences.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- OTTAWA & EASTERN ONTARIO ---
  {
    id: "cur-027",
    slug: "ottawa-tamil-association",
    name: "Ottawa Tamil Association (OTA)",
    tamilName: "ஒட்டாவா தமிழ் சங்கம்",
    category: "temples-community",
    city: "Ottawa",
    province: "ON",
    address: "Ottawa, ON",
    phone: "+1 613-288-8264",
    website: "https://ottawatamilassociation.ca/",
    email: "info@ottawatamilassociation.ca",
    description:
      "Connecting Tamil families across the National Capital Region — community sports, cultural days, youth programs, and language classes.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-028",
    slug: "tamarind-tiffin-ottawa",
    name: "Tamarind Tiffin Sri Lankan Kitchen",
    tamilName: "தமரிண்ட் டிபன்",
    category: "restaurants-takeout",
    city: "Ottawa",
    province: "ON",
    address: "1055 Bank St, Ottawa, ON K1S 3W9",
    phone: "+1 613-730-1010",
    website: "",
    email: "",
    description:
      "Authentic Ceylon curries, string hoppers, devilled cuttlefish, and vegetable kothu in the heart of Ottawa.",
    verified: true,
    featured: true,
    source: "curated",
  },

  // --- HAMILTON, KITCHENER, WATERLOO, LONDON (ON) ---
  {
    id: "cur-029",
    slug: "hamilton-tamil-cultural-association",
    name: "Hamilton Tamil Cultural Association",
    tamilName: "ஹாமில்டன் தமிழ் கலாச்சார சங்கம்",
    category: "temples-community",
    city: "Hamilton",
    province: "ON",
    address: "Hamilton, ON",
    phone: "+1 905-525-9140",
    website: "",
    email: "hamiltontamil@gmail.com",
    description:
      "Community hub supporting Tamil families, McMaster university students, and newcomers in Hamilton, Ancaster, and Burlington.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-030",
    slug: "waterloo-ceylon-kitchen",
    name: "Waterloo Ceylon Kitchen",
    tamilName: "வாட்டர்லூ சிலோன் கிச்சன்",
    category: "restaurants-takeout",
    city: "Waterloo",
    province: "ON",
    address: "255 King St N, Waterloo, ON N2J 4V2",
    phone: "+1 519-886-9090",
    website: "",
    email: "",
    description:
      "Popular spot for University of Waterloo and Laurier students & local tech professionals craving spicy kothu, rolls, and curries.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-031",
    slug: "london-tamil-community-services",
    name: "London Tamil Association & Services",
    tamilName: "லண்டன் தமிழ் சங்கம்",
    category: "temples-community",
    city: "London",
    province: "ON",
    address: "London, ON",
    phone: "+1 519-661-2111",
    website: "",
    email: "info@londontamils.ca",
    description:
      "Community organization in Southwestern Ontario coordinating Tamil school, cultural celebrations, and newcomer support.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- MONTREAL & QUEBEC (QC) ---
  {
    id: "cur-032",
    slug: "nanthus-bakery-montreal",
    name: "Nanthu's Bakery Kitchen",
    tamilName: "நந்துஸ் பேக்கரி & கிச்சன்",
    category: "bakeries-sweets",
    city: "Montreal",
    province: "QC",
    address: "6953 Victoria Ave, Montreal, QC H3W 2T6",
    phone: "+1 438-229-1768",
    website: "",
    email: "",
    description:
      "Iconic Montreal Tamil bakery on Victoria Avenue in Côte-des-Neiges — fresh mutton rolls, egg pastries, milk toffee, and daily short eats.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-033",
    slug: "montreal-durkai-amman-temple",
    name: "Sri Durkai Amman Temple Montreal",
    tamilName: "மொண்ட்ரியால் ஸ்ரீ துர்க்கை அம்மன் கோவில்",
    category: "temples-community",
    city: "Montreal",
    province: "QC",
    address: "2465 Rue Bélanger, Montréal, QC H2G 1E4",
    phone: "+1 514-722-7779",
    website: "",
    email: "",
    description:
      "The spiritual and cultural heartbeat of the Quebec Tamil community, hosting daily pujas, chariot festival (Ther), and cultural festivities.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-034",
    slug: "colombo-curry-house-montreal",
    name: "Colombo Curry House",
    tamilName: "கொழும்பு கறி ஹவுஸ்",
    category: "restaurants-takeout",
    city: "Montreal",
    province: "QC",
    address: "5155 Chemin Queen Mary, Montréal, QC H3W 1X4",
    phone: "+1 514-484-8882",
    website: "",
    email: "",
    description:
      "Traditional Sri Lankan Tamil curries, devilled pork/chicken, kothu roti, and weekend string hopper banquets.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-035",
    slug: "laval-tamil-grocery-services",
    name: "Laval Tamil Grocers & Spice House",
    tamilName: "லாவால் தமிழ் மளிகை",
    category: "grocery-supermarkets",
    city: "Laval",
    province: "QC",
    address: "1450 Boulevard Curé-Labelle, Laval, QC H7V 2W2",
    phone: "+1 450-681-4455",
    website: "",
    email: "",
    description:
      "Serving North Shore Montreal families with fresh produce, rice bags, South Indian masalas, and Sri Lankan snacks.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- VANCOUVER & METRO VANCOUVER (BC) ---
  {
    id: "cur-036",
    slug: "thurga-foods-vancouver",
    name: "Thurga Foods",
    tamilName: "துர்கா உணவுகள்",
    category: "grocery-supermarkets",
    city: "Vancouver",
    province: "BC",
    address: "6049 Fraser St, Vancouver, BC V5W 2Z8",
    phone: "+1 604-325-1100",
    website: "",
    email: "",
    description:
      "Metro Vancouver's primary Sri Lankan and Tamil grocery store on Fraser Street — Ceylon spices, frozen foods, hopper flour, and imported specialties.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-037",
    slug: "vancouver-murugan-temple",
    name: "B.C. Murugan Temple",
    tamilName: "பிரிட்டிஷ் கொலம்பியா முருகன் கோவில்",
    category: "temples-community",
    city: "Vancouver",
    province: "BC",
    address: "3134 140 St, Surrey, BC V4P 2B3",
    phone: "+1 604-536-7494",
    website: "https://bcmurugantemple.com/",
    email: "info@bcmurugantemple.com",
    description:
      "Central Hindu temple for BC Tamils — holy sanctum of Lord Murugan, conducting Thaipusam festivals, wedding blessings, and community meals.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-038",
    slug: "lanka-palace-surrey",
    name: "Lanka Palace Restaurant",
    tamilName: "லங்கா பேலஸ் உணவகம்",
    category: "restaurants-takeout",
    city: "Surrey",
    province: "BC",
    address: "9340 120 St, Surrey, BC V3V 4B9",
    phone: "+1 604-588-7711",
    website: "",
    email: "",
    description:
      "Sri Lankan Tamil dining in Fraser Valley — delicious seafood kothu, lamprais, hopper combos, and family-size weekend takeout trays.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-039",
    slug: "west-coast-tamil-law-burnaby",
    name: "West Coast Tamil Legal & Notary Services",
    tamilName: "வெஸ்ட் கோஸ்ட் தமிழ் சட்ட சேவை",
    category: "legal-immigration",
    city: "Burnaby",
    province: "BC",
    address: "4720 Kingsway, Burnaby, BC V5H 4N2",
    phone: "+1 604-434-2200",
    website: "",
    email: "legal@westcoasttamil.ca",
    description:
      "Real estate conveyancing, BC PNP immigration, family law, and commissioner of oaths serving Metro Vancouver Tamils.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- CALGARY & EDMONTON (AB) ---
  {
    id: "cur-040",
    slug: "calgary-murugan-temple",
    name: "Sri Murugan Society of Alberta (Calgary)",
    tamilName: "கல்கரி ஸ்ரீ முருகன் ஆலயம்",
    category: "temples-community",
    city: "Calgary",
    province: "AB",
    address: "4203 17 Ave SE, Calgary, AB T2A 0T2",
    phone: "+1 403-248-2838",
    website: "https://calgarymurugantemple.ca/",
    email: "info@calgarymurugantemple.ca",
    description:
      "Cultural & spiritual pillar for Alberta Tamils — daily pujas, Tamil school, Deepavali celebrations, and senior gatherings.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-041",
    slug: "ceylon-flavours-calgary",
    name: "Ceylon Flavours Restaurant & Takeout",
    tamilName: "சிலோன் ஃப்ளேவர்ஸ்",
    category: "restaurants-takeout",
    city: "Calgary",
    province: "AB",
    address: "3770 Westwinds Dr NE, Calgary, AB T3J 5H3",
    phone: "+1 403-293-6622",
    website: "",
    email: "",
    description:
      "Calgary's hot spot for Ceylon short eats, spicy mutton kothu, egg roti, and weekend Jaffna seafood curries.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-042",
    slug: "edmonton-maha-ganapathy-temple",
    name: "Maha Ganapathy Temple of Edmonton",
    tamilName: "எட்மண்டன் மகா கணபதி ஆலயம்",
    category: "temples-community",
    city: "Edmonton",
    province: "AB",
    address: "12838 52 St NW, Edmonton, AB T5A 3P8",
    phone: "+1 780-478-2244",
    website: "https://mahaganapathy.com/",
    email: "info@mahaganapathy.com",
    description:
      "Traditional granite deity temple serving Northern Alberta Tamil families with youth chanting, weddings, and grand annual festivals.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-043",
    slug: "jaffna-tiffins-edmonton",
    name: "Jaffna Tiffins & Spices Edmonton",
    tamilName: "யாழ்ப்பாணம் டிபன் & மசாலா",
    category: "restaurants-takeout",
    city: "Edmonton",
    province: "AB",
    address: "9210 34 Ave NW, Edmonton, AB T6E 5P2",
    phone: "+1 780-462-8811",
    website: "",
    email: "",
    description:
      "Authentic Northern Sri Lankan style dosai, mutton curries, kothu, and catering across Edmonton and surrounding communities.",
    verified: true,
    featured: true,
    source: "curated",
  },

  // --- WINNIPEG (MB) ---
  {
    id: "cur-044",
    slug: "manitoba-tamil-cultural-association",
    name: "Manitoba Tamil Cultural Association (MTCA)",
    tamilName: "மனிடோபா தமிழ் கலாச்சார சங்கம்",
    category: "temples-community",
    city: "Winnipeg",
    province: "MB",
    address: "Winnipeg, MB",
    phone: "+1 204-474-8800",
    website: "https://manitobatamils.com/",
    email: "contact@manitobatamils.com",
    description:
      "Uniting Tamil families across Manitoba — organizing Tamil New Year, Pongal festivals, youth sports leagues, and settlement guidance.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-045",
    slug: "spicy-banana-leaf-winnipeg",
    name: "Spicy Banana Leaf Sri Lankan Eats",
    tamilName: "ஸ்பைசி பனானா லீப்",
    category: "restaurants-takeout",
    city: "Winnipeg",
    province: "MB",
    address: "1855 Pembina Hwy, Winnipeg, MB R3T 2G6",
    phone: "+1 204-269-1234",
    website: "",
    email: "",
    description:
      "Authentic Ceylon curries, flaky roti, kothu, and short eats for Winnipeg and University of Manitoba students.",
    verified: true,
    featured: true,
    source: "curated",
  },

  // --- HALIFAX & ATLANTIC CANADA (NS / NL / NB / PE) ---
  {
    id: "cur-046",
    slug: "halifax-tamil-cultural-society",
    name: "Tamil Cultural Society of Nova Scotia",
    tamilName: "நோவா ஸ்கோஷியா தமிழ் கலாச்சார சங்கம்",
    category: "temples-community",
    city: "Halifax",
    province: "NS",
    address: "Halifax, NS",
    phone: "+1 902-420-5555",
    website: "",
    email: "novascotiatamils@gmail.com",
    description:
      "Active Atlantic Canada Tamil society connecting families, Dalhousie and Saint Mary's students, and healthcare professionals in Halifax & Dartmouth.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-047",
    slug: "st-johns-tamil-community-nl",
    name: "Newfoundland Tamil Community Association",
    tamilName: "நியூஃபவுண்ட்லாந்து தமிழ் சங்கம்",
    category: "temples-community",
    city: "St. John's",
    province: "NL",
    address: "St. John's, NL",
    phone: "+1 709-864-8000",
    website: "",
    email: "nltamils@gmail.com",
    description:
      "Community hub supporting Tamil families, physicians, engineers, and Memorial University scholars across Newfoundland & Labrador.",
    verified: true,
    featured: true,
    source: "curated",
  },

  // --- SASKATOON & REGINA (SK) ---
  {
    id: "cur-048",
    slug: "saskatoon-tamil-association",
    name: "Saskatoon Tamil Community Association",
    tamilName: "சாஸ்கடூன் தமிழ் சங்கம்",
    category: "temples-community",
    city: "Saskatoon",
    province: "SK",
    address: "Saskatoon, SK",
    phone: "+1 306-966-4343",
    website: "",
    email: "saskatoontamils@gmail.com",
    description:
      "Connecting Tamil residents in Saskatoon and the University of Saskatchewan campus with cultural events and language classes.",
    verified: true,
    featured: true,
    source: "curated",
  },

  // --- NATIONWIDE ONLINE SERVICES ---
  {
    id: "cur-049",
    slug: "tamilkadai-canada",
    name: "Tamilkadai Canada",
    tamilName: "தமிழ்கடை கனடா",
    category: "grocery-supermarkets",
    city: "Toronto",
    province: "ON",
    address: "Nationwide Online Store, Toronto, ON",
    phone: "+1 647-558-8822",
    website: "https://www.tamilkadai.ca/",
    email: "support@tamilkadai.ca",
    description:
      "Canada’s leading online Tamil grocery service shipping authentic spices, snacks, Jaffna curry powders, sweets, and cookware coast-to-coast.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-050",
    slug: "express-tamil-printing-canada",
    name: "Express Tamil Printing & Invitations",
    tamilName: "எக்ஸ்பிரஸ் தமிழ் பிரிண்டிங்",
    category: "printing-design",
    city: "Scarborough",
    province: "ON",
    address: "1920 Ellesmere Rd, Scarborough, ON M1H 2V6",
    phone: "+1 416-438-9900",
    website: "",
    email: "print@expresstamil.ca",
    description:
      "Specialists in luxury Tamil wedding invitation cards, event banners, business cards, signage, and temple flyers shipped Canada-wide.",
    verified: true,
    featured: false,
    source: "curated",
  },

  // --- COMPREHENSIVE CURATED TAMIL PROFESSIONALS & BUSINESSES ACROSS CANADA ---
  {
    id: "cur-051",
    slug: "gta-tamil-immigration-law",
    name: "GTA Tamil Immigration & Legal Counsel",
    tamilName: "ஜிடிஏ தமிழ் குடிவரவு சட்ட மையம்",
    category: "legal-immigration",
    city: "Scarborough",
    province: "ON",
    address: "2400 Midland Ave, Unit 208, Scarborough, ON M1S 5C1",
    phone: "+1 416-293-8822",
    website: "https://gtatamillegal.ca",
    email: "contact@gtatamillegal.ca",
    description:
      "Expert Canadian immigration services, Super Visa applications, PR spousal sponsorships, refugee appeals, student visa transitions, and official notary services in Tamil and English.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-052",
    slug: "scarborough-tamil-dental-clinic",
    name: "Scarborough Tamil Community Dental Centre",
    tamilName: "ஸ்கார்பரோ தமிழ் பல் மருத்துவமனை",
    category: "medical-dental",
    city: "Scarborough",
    province: "ON",
    address: "2155 Lawrence Ave E, Unit 12, Scarborough, ON M1P 2P5",
    phone: "+1 416-757-5500",
    website: "",
    email: "care@scarboroughtamildental.ca",
    description:
      "Full-service family dental clinic providing teeth cleaning, fillings, root canals, emergency dental pain relief, kids dentistry, and denture care with Tamil-speaking dentists and hygienists.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-053",
    slug: "markham-tamil-family-health-physio",
    name: "Markham Tamil Family Medical & Physio Clinic",
    tamilName: "மார்க்கம் குடும்ப மருத்துவ & பிசியோ மையம்",
    category: "medical-dental",
    city: "Markham",
    province: "ON",
    address: "7750 Markham Rd, Unit 104, Markham, ON L3S 0B2",
    phone: "+1 905-209-9000",
    website: "",
    email: "clinic@markhamtamilhealth.ca",
    description:
      "Comprehensive walk-in medical clinic, family physicians, physiotherapy, chiropractic adjustment, massage therapy, acupuncture, and motor vehicle accident (MVA) rehabilitation.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-054",
    slug: "canadian-tamil-super-visa-insurance",
    name: "Canadian Tamil Super Visa & Life Insurance Brokers",
    tamilName: "கனடிய தமிழ் சூப்பர் விசா & ஆயுள் காப்பீடு",
    category: "insurance",
    city: "Markham",
    province: "ON",
    address: "8000 Woodbine Ave, Suite 300, Markham, ON L3R 9Y5",
    phone: "+1 905-470-8899",
    website: "https://tamilsinsurance.ca",
    email: "info@tamilsinsurance.ca",
    description:
      "Specialist brokers providing lowest rates for Parents & Grandparents Super Visa medical insurance, whole life insurance, critical illness, visitor health coverage, and commercial business insurance.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-055",
    slug: "brampton-tamil-realtors-group",
    name: "Peel & GTA Tamil Real Estate Advisory Group",
    tamilName: "பீல் & ஜிடிஏ தமிழ் ரியல் எஸ்டேட்",
    category: "real-estate-property",
    city: "Brampton",
    province: "ON",
    address: "85 Peel Centre Dr, Unit 202, Brampton, ON L6T 4H6",
    phone: "+1 905-791-7700",
    website: "",
    email: "homes@peeltamilrealty.ca",
    description:
      "Top-performing Tamil realtors helping buyers, sellers, and investors with detached homes, townhouses, pre-construction VIP allocations, and commercial plaza acquisitions across Peel and York regions.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-056",
    slug: "toronto-tamil-carnatic-dance-academy",
    name: "Toronto Tamil Fine Arts & Bharatanatyam Academy",
    tamilName: "ரொறன்ரோ தமிழ் நுண்கலை & பரதநாட்டிய கல்லூரி",
    category: "tuition-education",
    city: "Toronto",
    province: "ON",
    address: "1550 Victoria Park Ave, North York, ON M1L 2T4",
    phone: "+1 416-751-8890",
    website: "",
    email: "arts@torontotamilfinearts.org",
    description:
      "Distinguished cultural academy offering certified graded training in Bharatanatyam, Carnatic vocal music, Veena, Mridangam, Violin, and Tamil language literacy examinations.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-057",
    slug: "scarborough-tamil-auto-collision-mechanics",
    name: "Scarborough Master Tamil Auto Mechanics & Body Shop",
    tamilName: "ஸ்கார்பரோ தமிழ் ஆட்டோ மெக்கானிக்",
    category: "auto-mechanics",
    city: "Scarborough",
    province: "ON",
    address: "1400 Kennedy Rd, Unit 18, Scarborough, ON M1P 2L7",
    phone: "+1 416-759-4400",
    website: "",
    email: "service@tamilautocare.ca",
    description:
      "Licensed automotive mechanics providing Ontario safety standard certificates, brake repair, transmission rebuilds, computerized engine diagnostics, winter tire changeover, and collision body repairs.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-058",
    slug: "sapphire-tamil-wedding-photography-cinema",
    name: "Sapphire Tamil Wedding Photography & Cinema",
    tamilName: "சபையர் தமிழ் திருமண புகைப்படம் & சினிமா",
    category: "photography-events",
    city: "Scarborough",
    province: "ON",
    address: "2200 Brock Rd, Scarborough, ON M1X 1E2",
    phone: "+1 416-890-4321",
    website: "https://sapphireweddingcinema.ca",
    email: "hello@sapphireweddingcinema.ca",
    description:
      "Award-winning South Asian & Tamil wedding photography and cinematic 4K films. Full-day coverage of Hindu wedding rituals, Manavarai mandap stages, receptions, pre-wedding couple shoots, and live streaming.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-059",
    slug: "kanchipuram-silks-saree-boutique-scarborough",
    name: "Sri Kanchipuram Pattu Saree Palace & Jewellery",
    tamilName: "ஸ்ரீ காஞ்சிபுரம் பட்டுச் சேலை அரண்மனை",
    category: "fashion-jewellery",
    city: "Scarborough",
    province: "ON",
    address: "2600 Lawrence Ave E, Unit 8, Scarborough, ON M1P 2R9",
    phone: "+1 416-752-1188",
    website: "",
    email: "info@kanchipurampattucanada.ca",
    description:
      "Authentic handwoven pure silk Kanchipuram bridal sarees, designer wedding pattu, temple border sarees, traditional veshtis, kids pavadai, custom blouse stitching, and 22K gold-plated temple jewelry.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-060",
    slug: "ceylon-air-travel-tours-toronto",
    name: "Ceylon Express Air Travel & Tours Canada",
    tamilName: "சிலோன் எக்ஸ்பிரஸ் ஏர் டிராவல்ஸ்",
    category: "travel-tours",
    city: "Toronto",
    province: "ON",
    address: "1200 Eglinton Ave E, Suite 210, Toronto, ON M3C 1H9",
    phone: "+1 416-444-8899",
    website: "https://ceylonexpresstravel.ca",
    email: "bookings@ceylonexpresstravel.ca",
    description:
      "TICO-certified travel agency specializing in best-price flight tickets to Colombo, Chennai, Jaffna, London, and Singapore with airlines like Qatar, Emirates, Etihad, Air Canada, and SriLankan Airlines.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-061",
    slug: "gta-tamil-general-contractors-renovations",
    name: "GTA Tamil Master Contractors & Home Renovations",
    tamilName: "ஜிடிஏ தமிழ் கட்டிட & புனரமைப்பு ஒப்பந்ததாரர்கள்",
    category: "construction-trades",
    city: "Markham",
    province: "ON",
    address: "7050 Woodbine Ave, Markham, ON L3R 4G8",
    phone: "+1 416-602-9988",
    website: "",
    email: "build@gtatamilcontractors.ca",
    description:
      "Licensed general contractors for legal basement second-suite conversions, luxury kitchen remodels, bathroom modernizations, licensed electrical panel upgrades, plumbing, roofing, and home extensions.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-062",
    slug: "ceylon-cargo-parcel-shipping-canada",
    name: "Ceylon Direct Sea & Air Cargo Shipping Canada",
    tamilName: "சிலோன் டைரக்ட் கார்கோ & பார்சல் சேவை",
    category: "transport-moving",
    city: "Scarborough",
    province: "ON",
    address: "1155 Tapscott Rd, Unit 14, Scarborough, ON M1X 1E9",
    phone: "+1 416-291-0022",
    website: "https://ceylondirectcargo.ca",
    email: "shipping@ceylondirectcargo.ca",
    description:
      "Fast and secure door-to-door sea container and air cargo shipping from Canada to Sri Lanka (Jaffna, Colombo, Batticaloa, Trincomalee) and India. Wooden boxes, barrels, electronics, and household relocations.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-063",
    slug: "veera-silambam-martial-arts-canada",
    name: "Veera Traditional Silambam & Martial Arts Academy",
    tamilName: "வீர பாரம்பரிய சிலம்பம் & தற்காப்புக் கலைக் கழகம்",
    category: "fitness-wellness",
    city: "Scarborough",
    province: "ON",
    address: "1350 Ellesmere Rd, Scarborough, ON M1P 2X9",
    phone: "+1 416-431-7788",
    website: "",
    email: "info@veerasilambam.ca",
    description:
      "Preserving ancient Tamil martial heritage through traditional Silambam staff combat, Adimurai, Kalaripayattu, youth fitness coaching, self-defense workshops, and annual championship tournament training.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-064",
    slug: "montreal-tamil-immigration-accounting",
    name: "Montreal Tamil Accounting & Immigration Advisory",
    tamilName: "மொண்ட்ரியால் தமிழ் கணக்கியல் & குடிவரவு மையம்",
    category: "accounting-financial",
    city: "Montreal",
    province: "QC",
    address: "5000 Rue Jean-Talon O, Montréal, QC H4P 1W9",
    phone: "+1 514-733-4411",
    website: "",
    email: "contact@montrealtamiltax.ca",
    description:
      "Bilingual (Tamil, French, English) accounting, Quebec personal and corporate tax filings, Revenu Québec representation, immigration settlement, CSQ guidance, and business registration across Greater Montreal.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-065",
    slug: "vancouver-tamil-business-network-law",
    name: "Vancouver Pacific Tamil Legal & Corporate Advisory",
    tamilName: "வான்கூவர் பசிபிக் தமிழ் சட்ட ஆலோசகர்கள்",
    category: "legal-immigration",
    city: "Vancouver",
    province: "BC",
    address: "555 W Georgia St, Suite 1500, Vancouver, BC V6B 1Z6",
    phone: "+1 604-688-9900",
    website: "https://pacifictamillegal.ca",
    email: "advisory@pacifictamillegal.ca",
    description:
      "Serving BC Tamils in Vancouver, Surrey, and Burnaby with commercial contracts, BC PNP immigration, residential real estate transactions, family estate planning, and Commissioner for Taking Affidavits.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-066",
    slug: "calgary-tamil-tax-mortgage-associates",
    name: "Calgary Tamil CPA & Mortgage Associates",
    tamilName: "கல்கரி தமிழ் சிபிஏ & மார்ட்கேஜ் நிறுவனம்",
    category: "accounting-financial",
    city: "Calgary",
    province: "AB",
    address: "32 Westwinds Cres NE, Calgary, AB T3J 5L3",
    phone: "+1 403-277-5588",
    website: "",
    email: "cpa@calgarytamiltax.ca",
    description:
      "Alberta CPA services, CRA personal & corporate tax preparation, business bookkeeping, first-time home buyer mortgage pre-approvals, and investment planning for families in Calgary and Edmonton.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-067",
    slug: "ottawa-tamil-tutoring-language-school",
    name: "Ottawa Tamil Academy & Math Tutoring Centre",
    tamilName: "ஒட்டாவா தமிழ் கல்வி & கணித மையம்",
    category: "tuition-education",
    city: "Ottawa",
    province: "ON",
    address: "2450 Lancaster Rd, Ottawa, ON K1B 4S5",
    phone: "+1 613-731-9922",
    website: "",
    email: "learning@ottawatamilacademy.ca",
    description:
      "Promoting academic excellence and cultural roots in the National Capital Region. High school math, physics, chemistry tutoring, Tamil language literacy classes, and AP/IB exam preparation.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-068",
    slug: "toronto-tamil-it-web-digital-agency",
    name: "TamilTech Solutions & Web Development Canada",
    tamilName: "தமிழ் டெக் சோலூஷன்ஸ் & இணைய வடிவமைப்பு",
    category: "it-web",
    city: "Toronto",
    province: "ON",
    address: "100 University Ave, Toronto, ON M5J 1V6",
    phone: "+1 647-490-3344",
    website: "https://tamiltechcanada.ca",
    email: "hello@tamiltechcanada.ca",
    description:
      "Custom software engineering, Next.js web application development, e-commerce storefronts, POS integration for restaurants, Google SEO ranking, and digital marketing for Canadian business owners.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-069",
    slug: "mississauga-tamil-beauty-bridal-studio",
    name: "Lavanya Tamil Bridal Hair, Makeup & Saree Draping",
    tamilName: "லாவண்யா தமிழ் பிரைடல் மேக்கப் & சலூன்",
    category: "salons-beauty",
    city: "Mississauga",
    province: "ON",
    address: "700 Dundas St E, Mississauga, ON L4Y 3Y5",
    phone: "+1 905-279-3388",
    website: "",
    email: "bookings@lavanyabridal.ca",
    description:
      "Luxury bridal hair & high-definition makeup, traditional Muhurtham silk saree pleating and draping, intricate organic mehendi artistry, hydra facials, and complete pre-bridal beauty packages.",
    verified: true,
    featured: true,
    source: "curated",
  },
  {
    id: "cur-070",
    slug: "ajax-durham-tamil-driving-school",
    name: "Ajax & Durham Region Tamil Driving Academy",
    tamilName: "டர்காம் தமிழ் டிரைவிங் அகாடமி",
    category: "tuition-education",
    city: "Ajax",
    province: "ON",
    address: "15 Westney Rd N, Ajax, ON L1T 1P4",
    phone: "+1 905-686-2244",
    website: "",
    email: "drive@durhamtamildriving.ca",
    description:
      "MTO-approved beginner driver education (BDE) courses, G2 and G road test preparation, defensive driving techniques, and dual-brake car rentals with patient Tamil and English instructors.",
    verified: true,
    featured: true,
    source: "curated",
  },

  {
    id: "cur-080",
    slug: "sri-varasiththi-vinaayagar-temple",
    name: "Sri Varasiththi Vinaayagar Hindu Temple",
    tamilName: "ஸ்ரீ வரசித்தி விநாயகர் ஆலயம்",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "2701 Markham Rd, Scarborough, ON M1X 1M4",
    phone: "+1 416-299-5006",
    website: "https://www.vinaayagar.com/",
    email: "info@vinaayagar.com",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Varasiththi Vinaayagar (Maha Ganapathy). Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-081",
    slug: "nallur-murugan-temple-toronto",
    name: "Toronto Sri Murugan Kovil (Nallur Heritage)",
    tamilName: "ரொறன்ரோ ஸ்ரீ முருகன் கோவில் (நல்லூர் மரபு)",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "3825 Sheppard Ave E, Scarborough, ON M1T 3L4",
    phone: "+1 416-291-7891",
    website: "https://www.torontomurugankovil.org/",
    email: "admin@torontomurugankovil.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Lord Shanmukha Murugan with Valli & Devasena. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-082",
    slug: "canada-sri-kanthaswamy-kovil",
    name: "Canada Sri Kanthaswamy Kovil",
    tamilName: "கனடா ஸ்ரீ கந்தசுவாமி கோவில்",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "733 Birchmount Rd, Scarborough, ON M1K 1R5",
    phone: "+1 416-759-4674",
    website: "https://www.kanthaswamy.org/",
    email: "info@kanthaswamy.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Kanthaswamy (Lord Murugan). Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-083",
    slug: "sri-meenakshi-amman-temple-toronto",
    name: "Sri Meenakshi Amman Temple Toronto",
    tamilName: "ஸ்ரீ மீனாட்சி அம்மன் ஆலயம் ரொறன்ரோ",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "170 Nugget Ave, Scarborough, ON M1S 3A7",
    phone: "+1 416-291-7272",
    website: "https://www.meenakshitemple.ca/",
    email: "info@meenakshitemple.ca",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Goddess Meenakshi & Lord Sundareswarar. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-084",
    slug: "sri-nagapooshani-amman-temple",
    name: "Sri Nagapooshani Amman Temple (Nainativu Heritage)",
    tamilName: "ஸ்ரீ நாகபூஷணி அம்மன் ஆலயம் (நயினாதீவு மரபு)",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "5637 Finch Ave E, Scarborough, ON M1B 2T9",
    phone: "+1 416-298-9071",
    website: "https://www.nainativuamman.ca/",
    email: "info@nainativuamman.ca",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Bhuvaneswari Sri Nagapooshani Amman. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-085",
    slug: "sri-raja-rajeswari-amman-temple",
    name: "Sri Raja Rajeswari Amman Temple Toronto",
    tamilName: "ஸ்ரீ ராஜராஜேஸ்வரி அம்மன் ஆலயம்",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "2670 Midland Ave, Scarborough, ON M1S 3V6",
    phone: "+1 416-291-7253",
    website: "https://www.rajarajeswari.ca/",
    email: "contact@rajarajeswari.ca",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Lalitha Maha Tripurasundari (Raja Rajeswari). Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-086",
    slug: "toronto-sri-venkata-krishna-temple",
    name: "Toronto Sri Venkata Krishna Temple",
    tamilName: "ரொறன்ரோ ஸ்ரீ வேங்கட கிருஷ்ணா கோவில் (பெருமாள் கோவில்)",
    category: "temples-community",
    city: "North York",
    province: "ON",
    address: "481 McNicoll Ave, North York, ON M2H 2C9",
    phone: "+1 416-499-2999",
    website: "https://www.torontosrivenkatakrishna.org/",
    email: "info@torontosrivenkatakrishna.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Lord Venkateshwara (Balaji) & Lord Krishna. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-087",
    slug: "sri-mariamman-temple-toronto",
    name: "Sri Mariamman Kovil Toronto",
    tamilName: "ஸ்ரீ மாரியம்மன் கோவில் ரொறன்ரோ",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "110 Finchdene Sq, Scarborough, ON M1X 1B1",
    phone: "+1 416-293-6274",
    website: "https://www.srimariamman.ca/",
    email: "info@srimariamman.ca",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Mother Sri Maha Mariamman. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-088",
    slug: "sri-mathura-meenakshi-amman-kovil",
    name: "Sri Mathura Meenakshi Amman Kovil",
    tamilName: "ஸ்ரீ மதுரா மீனாட்சி அம்மன் கோவில்",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "3085 Markham Rd, Scarborough, ON M1X 1L6",
    phone: "+1 416-292-6284",
    website: "https://www.mathurameenakshi.ca/",
    email: "contact@mathurameenakshi.ca",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Goddess Mathura Meenakshi. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-089",
    slug: "canada-thiruchendur-murugan-kovil",
    name: "Canada Thiruchendur Murugan Kovil",
    tamilName: "கனடா திருச்செந்தூர் முருகன் கோவில்",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "385 Passmore Ave, Scarborough, ON M1X 1B6",
    phone: "+1 416-291-0385",
    website: "https://www.thiruchendurcanada.org/",
    email: "info@thiruchendurcanada.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Senthilandavar (Thiruchendur Murugan). Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-090",
    slug: "canada-sri-sanathan-shivan-kovil",
    name: "Canada Sri Sanathan Shivan Kovil (Sivan Temple)",
    tamilName: "கனடா ஸ்ரீ சனாதன சிவன் கோவில்",
    category: "temples-community",
    city: "Scarborough",
    province: "ON",
    address: "1200 Markham Rd, Scarborough, ON M1H 2Y9",
    phone: "+1 416-438-5182",
    website: "https://www.sivankovil.org/",
    email: "info@sivankovil.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Kailasanathar (Lord Shiva Lingam). Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-091",
    slug: "sri-sunderaraja-perumal-temple-markham",
    name: "Sri Sunderaraja Perumal Temple Markham",
    tamilName: "ஸ்ரீ சுந்தரராஜ பெருமாள் கோவில் மார்க்கம்",
    category: "temples-community",
    city: "Markham",
    province: "ON",
    address: "7050 Woodbine Ave, Markham, ON L3R 4G8",
    phone: "+1 905-470-8889",
    website: "https://www.sunderarajaperumal.org/",
    email: "info@sunderarajaperumal.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Sunderaraja Perumal (Lord Vishnu) with Sridevi & Bhoodevi. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-092",
    slug: "brampton-sri-sivasubramaniya-swamy-kovil",
    name: "Brampton Sri Sivasubramaniya Swamy Kovil",
    tamilName: "பிரம்டன் ஸ்ரீ சிவசுப்பிரமணிய சுவாமி கோவில்",
    category: "temples-community",
    city: "Brampton",
    province: "ON",
    address: "147 Wilkinson Rd, Brampton, ON L6T 4X1",
    phone: "+1 905-455-8889",
    website: "https://www.bramptonmurugan.com/",
    email: "info@bramptonmurugan.com",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Sivasubramaniya Swamy (Lord Murugan). Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-093",
    slug: "brampton-sri-ganesha-durga-temple",
    name: "Brampton Sri Ganesha Durga Hindu Temple",
    tamilName: "பிரம்டன் ஸ்ரீ கணேச துர்கா இந்து ஆலயம்",
    category: "temples-community",
    city: "Brampton",
    province: "ON",
    address: "247 Advance Blvd, Brampton, ON L6T 4H9",
    phone: "+1 905-799-0099",
    website: "https://www.ganeshadurga.org/",
    email: "info@ganeshadurga.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Siddhi Vinayagar & Goddess Durga. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-094",
    slug: "sri-siva-sathyanarayana-swamy-temple",
    name: "Sri Siva Sathyanarayana Swamy Temple Mississauga",
    tamilName: "ஸ்ரீ சிவ சத்யநாராயண சுவாமி கோவில் மிசிசாகா",
    category: "temples-community",
    city: "Mississauga",
    province: "ON",
    address: "3058 Hurontario St, Mississauga, ON L5B 1N7",
    phone: "+1 905-272-9993",
    website: "https://www.sivasathyanarayana.org/",
    email: "contact@sivasathyanarayana.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Lord Shiva & Lord Sathyanarayana. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-095",
    slug: "pickering-arulmigu-aruljothy-shivan-temple",
    name: "Pickering Arulmigu Aruljothy Shivan Temple",
    tamilName: "பிக்கரிங் அருள்மிகு அருள்ஜோதி சிவன் ஆலயம்",
    category: "temples-community",
    city: "Pickering",
    province: "ON",
    address: "1730 McPherson Crt, Unit 20, Pickering, ON L1W 3E6",
    phone: "+1 905-837-2448",
    website: "https://www.aruljothy.org/",
    email: "info@aruljothy.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Aruljotheeswarar (Lord Shiva Lingam). Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-096",
    slug: "durham-sri-pillaiyar-temple-ajax",
    name: "Durham Sri Pillaiyar Temple Ajax",
    tamilName: "துர்ஹாம் ஸ்ரீ பிள்ளையார் கோவில் அஜாக்ஸ்",
    category: "temples-community",
    city: "Ajax",
    province: "ON",
    address: "150 Westney Rd S, Ajax, ON L1S 2N9",
    phone: "+1 905-686-9090",
    website: "https://www.durhampillaiyar.ca/",
    email: "info@durhampillaiyar.ca",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Karpaga Vinayagar. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-097",
    slug: "ottawa-sri-murugan-kovil",
    name: "Ottawa Sri Murugan Kovil (Ottawa Hindu Society)",
    tamilName: "ஒட்டாவா ஸ்ரீ முருகன் கோவில்",
    category: "temples-community",
    city: "Ottawa",
    province: "ON",
    address: "4865 Bank St, Gloucester, Ottawa, ON K1X 1G6",
    phone: "+1 613-822-1531",
    website: "https://www.ottawahindutemple.com/",
    email: "info@ottawahindutemple.com",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Lord Shanmukha Murugan with Valli & Devasena. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-098",
    slug: "hamilton-hindu-samajam-murugan-temple",
    name: "Hamilton Hindu Samajam & Murugan Temple",
    tamilName: "ஹமில்டன் இந்து சமாஜம் & முருகன் கோவில்",
    category: "temples-community",
    city: "Hamilton",
    province: "ON",
    address: "440 Cloverdale Ave, Hamilton, ON L8K 4S7",
    phone: "+1 905-594-1188",
    website: "https://www.hamiltonhindutemple.com/",
    email: "info@hamiltonhindutemple.com",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Lord Murugan & Lord Shiva. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-099",
    slug: "kitchener-waterloo-hindu-temple",
    name: "Kitchener-Waterloo Hindu Cultural & Murugan Temple",
    tamilName: "கிச்சனர்-வாட்டர்லூ இந்துக் கலாச்சார முருகன் கோவில்",
    category: "temples-community",
    city: "Kitchener",
    province: "ON",
    address: "51 Stephan Crt, Kitchener, ON N2E 2S2",
    phone: "+1 519-743-7377",
    website: "https://www.kwhindutemple.ca/",
    email: "contact@kwhindutemple.ca",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Lord Ganesha, Murugan & Lord Shiva. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-100",
    slug: "sri-thiru-murugan-temple-montreal",
    name: "Sri Thiru Murugan Temple Montreal (DDO)",
    tamilName: "ஸ்ரீ திருமுருகன் கோவில் மொன்றியல் (டி.டி.ஓ)",
    category: "temples-community",
    city: "Dollard-des-Ormeaux",
    province: "QC",
    address: "1611 Blvd Saint-Régis, Dollard-des-Ormeaux, QC H9B 3H7",
    phone: "+1 514-683-8044",
    website: "https://www.montrealmurugan.org/",
    email: "info@montrealmurugan.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Shanmukha Murugan with Valli & Devasena. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-101",
    slug: "montreal-sri-maha-ganapathi-temple",
    name: "Montreal Sri Maha Ganapathi Temple",
    tamilName: "மொன்றியல் ஸ்ரீ மகா கணபதி ஆலயம்",
    category: "temples-community",
    city: "Montréal",
    province: "QC",
    address: "5335 Rue Jean-Talon O, Montreal, QC H4P 1X4",
    phone: "+1 514-738-4447",
    website: "https://www.mahaganapathi.ca/",
    email: "info@mahaganapathi.ca",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Maha Ganapathi. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-102",
    slug: "bc-murugan-temple-surrey",
    name: "B.C. Murugan Temple (Sri Murugan Society of BC)",
    tamilName: "பி.சி. முருகன் கோவில் (பிரிட்டிஷ் கொலம்பியா)",
    category: "temples-community",
    city: "Surrey",
    province: "BC",
    address: "3134 140 St, Surrey, BC V3W 5H6",
    phone: "+1 604-599-4111",
    website: "https://www.bcmurugan.org/",
    email: "info@bcmurugan.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Lord Balamurugan (Sri Shanmukha). Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-103",
    slug: "vancouver-sri-ganesh-temple",
    name: "Vancouver Sri Ganesh Temple",
    tamilName: "வான்கூவர் ஸ்ரீ கணேஷ் ஆலயம்",
    category: "temples-community",
    city: "Vancouver",
    province: "BC",
    address: "2092 Kingsway, Vancouver, BC V5N 2T3",
    phone: "+1 604-874-5544",
    website: "https://www.vancouverganeshtemple.org/",
    email: "info@vancouverganeshtemple.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Maha Ganapathy. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-104",
    slug: "maha-ganapathy-temple-edmonton",
    name: "Maha Ganapathy Temple of Edmonton",
    tamilName: "மகா கணபதி ஆலயம் எட்மன்ரன்",
    category: "temples-community",
    city: "Edmonton",
    province: "AB",
    address: "12838 52 St NW, Edmonton, AB T5A 3P8",
    phone: "+1 780-478-4100",
    website: "https://www.mahaganapathitemple.com/",
    email: "info@mahaganapathitemple.com",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Sri Maha Ganapathy. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-105",
    slug: "winnipeg-hindu-temple-murugan",
    name: "Hindu Society of Manitoba (Winnipeg Hindu Temple)",
    tamilName: "இந்து சமூகம் மனிடோபா (வின்னிபெக் இந்துக் கோவில்)",
    category: "temples-community",
    city: "Winnipeg",
    province: "MB",
    address: "999 St Anne's Rd, Winnipeg, MB R2N 4G5",
    phone: "+1 204-257-2274",
    website: "https://www.hindusocietyofmanitoba.com/",
    email: "info@hindusocietyofmanitoba.com",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Lord Murugan, Sri Ganesha & Lord Shiva. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-106",
    slug: "halifax-hindu-temple-tamil-society",
    name: "Halifax Hindu Temple & Tamil Cultural Mandapam",
    tamilName: "ஹாலிஃபாக்ஸ் இந்துக் கோவில் & தமிழ் கலாச்சார மண்டபம்",
    category: "temples-community",
    city: "Halifax",
    province: "NS",
    address: "111 Kearney Lake Rd, Halifax, NS B3M 4H1",
    phone: "+1 902-443-4240",
    website: "https://www.halifaxhindutemple.ca/",
    email: "contact@halifaxhindutemple.ca",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Lord Murugan, Sri Ganesha & Mother Durga. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "cur-107",
    slug: "saskatoon-hindu-temple",
    name: "Saskatoon Hindu Temple & Murugan Shrine",
    tamilName: "சஸ்கடூன் இந்துக் கோவில் & முருகன் சந்நிதி",
    category: "temples-community",
    city: "Saskatoon",
    province: "SK",
    address: "107 Albert Ave, Saskatoon, SK S7N 1E7",
    phone: "+1 306-653-5683",
    website: "https://www.saskatoonhindutemple.org/",
    email: "info@saskatoonhindutemple.org",
    description: "Revered Canadian Tamil Hindu temple. Pradhana Moorthi: Lord Murugan & Sri Siddhi Vinayagar. Daily 4-Kala poojas, darshan hours, and annual Thiruvizha festivals.",
    hours: "Open Daily with 4-Kala Daily Poojas",
    verified: true,
    featured: true,
    claimed: true,
    plan: "featured",
    source: "curated",
    createdAt: "2026-01-01T00:00:00Z"
  },
];
